### ISSUE TITLE
spdy-http2 module crash fix

### ISSUE THREAD

**Issue by Jaeiya** [Noumenae/server#20]
There's a memory leak with the SPDY http2 module that should be fixed by using the directions here:
https://github.com/spdy-http2/spdy-transport/issues/47

**Comment by Aedaeum** [comment]
I tried to address this, but the fix doesn't seem to be appropriate for the file that it's designed to "fix". Right now I'm not having any issues, so we will just keep an eye on this for the future

**Comment by vytautas-pranskunas-** [comment]
Any progresss?

**Comment by Aedaeum** [comment]
I can't reproduce the issue, so there's not much I can do. It only happened that one time and it's been solid ever since... When I can find a way to reliably reproduce this, I will attempt again, unless the new version comes out which will make this issue moot.

**Comment by vytautas-pranskunas-** [comment]
Clone angular universal starter. Npm i. Add spdy with http2 push.

**Comment by Aedaeum** [comment]
I'll take a look at that when I have some time, currently busy with another project right now.

**Comment by vytautas-pranskunas-** [comment]
I am using you workaround and it works but it creats bad feeling about those memory leaks...?

**Comment by Aedaeum** [comment]
I took a look at other developments and it appears google is dropping its SPDY support regardless, which means native http2 is on the horizon.

https://gigaom.com/2015/02/09/google-ditches-its-own-protocol-for-http2-and-a-faster-web/

That being said, in the meantime, the fix should be enough to get you through until express 5: https://twitter.com/matteocollina/status/924985689799823360?ref_src=twsrc%5Etfw

**Comment by vytautas-pranskunas-** [comment]
I am fine with that fix if only memory leacks are not comming. Should I apply this also https://github.com/spdy-http2/spdy-transport/pull/48 ?

**Comment by Jaeiya** [comment]
This has been fixed in the latest versions of SPDY and I've already updated my v2 branch to v4.0.0.
